#!/usr/bin/env bash
#
# Human-in-the-loop SERL, end to end, with no hardware required.
#
#   ./scripts/run_hil_serl.sh <task> demos [N]   # expert drives; records N demos
#   ./scripts/run_hil_serl.sh <task> learner     # terminal 1
#   ./scripts/run_hil_serl.sh <task> actor       # terminal 2 (expert intervenes)
#   ./scripts/run_hil_serl.sh <task> eval [N]    # headless, writes N MP4s
#   ./scripts/run_hil_serl.sh <task> all         # smoke: demos -> short run -> eval
#
# <task> is insert_sim or insert_maniskill; the _hil config variant is selected
# automatically.  Demonstrations are generated by a scripted expert standing in
# for a human, so nothing is downloaded and no SpaceMouse is needed.
#
# On a machine that does have a SpaceMouse:
#   EXPERT=spacemouse TRIGGER=manual ./scripts/run_hil_serl.sh insert_sim actor

set -euo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")/.."

TASK_ARG="${1:-}"
[[ -n "${TASK_ARG}" ]] || { echo "Missing <task>." >&2; TASK_ARG="--help"; }
case "${TASK_ARG}" in
    -h|--help|help)
        sed -n '2,17p' "${BASH_SOURCE[0]}" | sed 's/^# \?//'
        exit 0
        ;;
esac
shift

# Accept the base task name, the _hil variant, or a _human teleoperation
# variant.  Only the first two are interchangeable -- appending _hil to a
# _human task would name a config that does not exist.
case "${TASK_ARG}" in
    *_human)
        EXP_NAME="${TASK_ARG}"
        BASE_TASK="${TASK_ARG%_human}"
        ;;
    *)
        EXP_NAME="${TASK_ARG%_hil}_hil"
        BASE_TASK="${TASK_ARG%_hil}"
        ;;
esac

CHECKPOINT_PATH="${CHECKPOINT_PATH:-checkpoints/${EXP_NAME}}"
DEMO_PATH="${DEMO_PATH:-demo_data/${EXP_NAME}_demos.pkl}"
SEED="${SEED:-42}"

# The ManiSkill scene's human-render camera is named `render_camera`; the flag's
# `front` default does not exist there and evaluation would crash.
case "${BASE_TASK}" in
    insert_maniskill) EVAL_MAIN_CAMERA="${EVAL_MAIN_CAMERA:-render_camera}" ;;
    *)                EVAL_MAIN_CAMERA="${EVAL_MAIN_CAMERA:-front}" ;;
esac

# Optional per-run overrides of the config's `hil` block, so switching to real
# hardware needs no file edit.
HIL_OVERRIDES=()
[[ -n "${EXPERT:-}" ]] && HIL_OVERRIDES+=(--config_override="hil.expert=${EXPERT}")
[[ -n "${TRIGGER:-}" ]] && HIL_OVERRIDES+=(--config_override="hil.trigger=${TRIGGER}")
[[ -n "${THRESHOLD:-}" ]] && \
    HIL_OVERRIDES+=(--config_override="hil.disagreement_threshold=${THRESHOLD}")

# train_serl always initializes Weights & Biases, and wandb aborts the process
# outright when no API key is configured -- the learner dies before its first
# step, and the actor is left retrying against a server that will never come up.
# Default to the flag that puts wandb in disabled mode unless a key is present,
# so a fresh clone can run the smoke test.  Set DEBUG=0 to force real logging.
TRAIN_FLAGS=()
if [[ "${DEBUG:-auto}" == "1" ]]; then
    TRAIN_FLAGS+=(--debug)
elif [[ "${DEBUG:-auto}" == "auto" ]]; then
    if [[ -z "${WANDB_API_KEY:-}" && ! -f "${HOME}/.netrc" ]]; then
        echo ">>> no WANDB_API_KEY and no ~/.netrc: passing --debug (wandb disabled)" >&2
        TRAIN_FLAGS+=(--debug)
    fi
fi

# Resolve uv even when PATH is minimal (cron, non-login shells, IDE terminals).
UV="${UV:-$(command -v uv || true)}"
if [[ -z "${UV}" ]]; then
    for candidate in "${HOME}/.local/bin/uv" /usr/local/bin/uv; do
        [[ -x "${candidate}" ]] && UV="${candidate}" && break
    done
fi
if [[ -z "${UV}" ]]; then
    echo "uv not found. Install it, or set UV=/path/to/uv." >&2
    exit 1
fi

usage() {
    sed -n '2,17p' "${BASH_SOURCE[0]}" | sed 's/^# \?//'
    exit "${1:-1}"
}

# `trigger=always` hands the whole episode to the expert, which is how demos get
# bootstrapped without a human.  The expert is not perfect, hence --max_attempts.
# A human operator wants `manual` instead -- they are not pushing on every step,
# and `always` would record their idle steps as deliberate zero actions:
#   DEMO_TRIGGER=manual EXPERT=keyboard ./scripts/run_hil_serl.sh insert_sim demos 10
demos() {
    local n="${1:-20}"
    shift || true
    local attempts=$(( n * 3 ))
    mkdir -p demo_data
    "${UV}" run python train/record_demo.py \
        --exp_name="${EXP_NAME}" \
        --successes_needed="${n}" \
        --max_attempts="${MAX_ATTEMPTS:-${attempts}}" \
        --seed="${SEED}" \
        --config_override="hil.trigger=${DEMO_TRIGGER:-always}" \
        "${HIL_OVERRIDES[@]}" "$@"
    # record_demo.py timestamps its output; expose the newest under a stable name.
    local newest
    newest="$(ls -t demo_data/${EXP_NAME}_*_demos_*.pkl 2>/dev/null | head -1)"
    [[ -n "${newest}" ]] || { echo "No demo file was produced." >&2; exit 1; }
    ln -sf "$(basename "${newest}")" "${DEMO_PATH}"
    echo ">>> ${DEMO_PATH} -> ${newest}"
}

learner() {
    [[ -e "${DEMO_PATH}" ]] || {
        echo "Missing ${DEMO_PATH}. Run '$0 ${BASE_TASK} demos' first." >&2
        exit 1
    }
    mkdir -p "${CHECKPOINT_PATH}"
    "${UV}" run python -m train.train_serl \
        --exp_name="${EXP_NAME}" \
        --demo_path="${DEMO_PATH}" \
        --checkpoint_path="${CHECKPOINT_PATH}" \
        --seed="${SEED}" \
        "${HIL_OVERRIDES[@]}" "${TRAIN_FLAGS[@]}" \
        --learner "$@"
}

actor() {
    mkdir -p "${CHECKPOINT_PATH}"
    "${UV}" run python -m train.train_serl \
        --exp_name="${EXP_NAME}" \
        --checkpoint_path="${CHECKPOINT_PATH}" \
        --seed="${SEED}" \
        --eval_video_main_camera="${EVAL_MAIN_CAMERA}" \
        "${HIL_OVERRIDES[@]}" "${TRAIN_FLAGS[@]}" \
        --actor "$@"
}

# Evaluation runs the learned policy alone: the expert must not be in the loop,
# or the numbers would measure the expert.
evaluate() {
    local n_trajs="${1:-10}"
    shift || true
    "${UV}" run python -m train.train_serl \
        --exp_name="${EXP_NAME}" \
        --checkpoint_path="${CHECKPOINT_PATH}" \
        --seed="${SEED}" \
        --eval_n_trajs="${n_trajs}" \
        --eval_video_main_camera="${EVAL_MAIN_CAMERA}" \
        --config_override="hil.enabled=false" \
        "${TRAIN_FLAGS[@]}" \
        --actor "$@"
}

all() {
    local n_demos="${SMOKE_DEMOS:-5}"
    local n_steps="${SMOKE_STEPS:-2000}"
    local n_eval="${SMOKE_EVAL:-3}"
    # The task configs checkpoint every 5000 steps, which a short smoke run
    # never reaches -- evaluation would then abort with "no checkpoint found".
    # Checkpoint twice within whatever budget the smoke run is given.
    local ckpt_period="${SMOKE_CHECKPOINT_PERIOD:-$(( n_steps / 2 ))}"
    (( ckpt_period > 0 )) || ckpt_period=1

    echo ">>> [1/3] recording ${n_demos} expert demos"
    demos "${n_demos}"

    echo ">>> [2/3] learner + actor for ${n_steps} steps"
    mkdir -p "${CHECKPOINT_PATH}"
    learner --config_override="training.max_steps=${n_steps}" \
            --config_override="training.checkpoint_period=${ckpt_period}" &
    local learner_pid=$!
    # Both halves talk over localhost; killing the pair together avoids a
    # stranded learner holding the port on the next run.
    trap 'kill ${learner_pid} 2>/dev/null || true' EXIT
    sleep 20
    # A learner that died during startup (missing wandb key, occupied port) is
    # otherwise invisible: the actor just retries the connection until the
    # timeout, and the run looks slow rather than broken.
    if ! kill -0 "${learner_pid}" 2>/dev/null; then
        echo "Learner exited during startup; see the traceback above." >&2
        trap - EXIT
        exit 1
    fi
    actor --config_override="training.max_steps=${n_steps}" || true
    wait "${learner_pid}" 2>/dev/null || true
    trap - EXIT

    echo ">>> [3/3] evaluating ${n_eval} trajectories"
    evaluate "${n_eval}"
    echo ">>> videos in ${CHECKPOINT_PATH}/videos"
}

command="${1:-}"
shift || true
case "${command}" in
    demos) demos "$@" ;;
    learner) learner "$@" ;;
    actor) actor "$@" ;;
    eval|evaluate) evaluate "$@" ;;
    all) all "$@" ;;
    -h|--help|help) usage 0 ;;
    *) echo "Unknown command: ${command:-<none>}" >&2; usage 1 ;;
esac
